a = input('\033[1;33mDigite qualquer coisa:\033[1;34m')
cores = {'normal':'\033[m', 'preto':'\033[30m', 'vermelho':'\033[31m', 'verde':'\033[32m', 'branco':'\033[97m'}
print(type(a))
print(f'{cores["vermelho"]}Os caracteres digitados estao em ordem alfanumeria? {cores["verde"]}{a.isalnum()}')
print(f'{cores["vermelho"]}Todos os caracteres digitados sao letras? {cores["verde"]}{a.isalpha()}')
print(f'{cores["vermelho"]}Caracteres sao ASCII? {cores["verde"]}{a.isascii()}')
print(f'{cores["vermelho"]}Carcteres sao decimais? {cores["verde"]}{a.isdecimal()}')
print(f'{cores["vermelho"]}Todos os caractes sao numeros? {cores["verde"]}{a.isdigit()}')
print(f'{cores["normal"]}{a} {cores["vermelho"]}é um identificador? {cores["verde"]}{a.isidentifier()}')
print(f'{cores["vermelho"]}Todos os caracteres estao em minusculo? {cores["verde"]}{a.islower()}')
print(f'{cores["vermelho"]}Todos os caracteres sao numericos? {cores["verde"]}{a.isnumeric()}')
print(f'{cores["vermelho"]}Todos os valores podem ser exibidos? {cores["verde"]}{a.isprintable()}')
print(f'{cores["branco"]}N digitou Espaços?? {cores["verde"]}{a.isspace()}')
print(f'{cores["vermelho"]}maiuscula e o resto minuscula? {cores["verde"]}{a.istitle()}')
print(f'{cores["vermelho"]}Todas as letras sao Mauslulas? {cores["verde"]}{a.isupper()}')
